name: deep-mlsa
channels:
- default
dependencies:
- python=3.5
- pip
- pip:
  - Keras==1.2.1
  - tqdm==4.10
  - Theano==0.8.2
  - tensorflow-gpu==0.12.1
  - gensim==0.13.3
  - nltk==3.2.1
  - scipy==0.18.1
  - torch
