stages:
  step0_Training:
    cmd: python runner.py -c mlsa_train/config_supervised_en.json
    deps:
    - runner.py
    - configurations/mlsa_evaluate/config_supervised_en.json
    - data/supervised_phase/en_full
  step1_Evaluate:
    cmd: python runner.py -c data/mlsa_evaluate/config_supervised_en.json
    deps:
    - runner.py
    - data/mlsa_evaluate/config_supervised_en.json
    - data/supervised_phase/en_full
